language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: "pip install -r requirements-ci.txt"
script:
  - pytest
  - pycodestyle monty
  - pydocstyle monty
  - mypy monty tests
  - flake8 --count --show-source --statistics monty
  - pylint monty
