language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: "pip install -r requirements-ci.txt"
script:
  - pytest
  - pycodestyle monty
  - pydocstyle monty
  - mypy
  - flake8 --count --show-source --statistics monty